name: Deploy React App to Github Pages
on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: v16.17.0
    - name: Install dependencies
      run: npm ci
    - name: Deploy
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git config user.name github-actions-bot
        git config user.email support+actions@github.com
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MapboxAccessToken: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
