name: Deploy React App to Github Pages
on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: v16.17.0
    - name: Install dependencies
      run: npm ci
    - name: Deploy
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm run deploy
